version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          dependency_type: "production"
          update_type: "all"
      - match:
          dependency_type: "direct"
          update_type: "security"
